site_name: docs/0.12.x


plugins:
    - search

hooks:
    - hooks/env_key_wrap.py

nav:
    - Concepts: concepts.md
    - API:
          - Catalog: api/catalog.md
          - Generic Tables: api/generic-table.md
          - Management (Core): api/management.md
          - Management <span class="lkp"></span>: api/management-plus.md
    - Query Engines: engines.md
    - User Guide:
          - bootstrap.md
          - storage.md
          - authentication.md
          - authorization.md
          - Authorization (OpenFGA): authorization-openfga.md
          - Authorization (Cedar): authorization-cedar.md
          - View Security: view-security.md
          - Generic Tables: generic-tables.md
          - logging.md
          - monitoring.md
          - opa.md
          - table-maintenance.md
          - production.md
          - gotchas.md
    - Configuration: configuration.md
    - Contribute:
          - developer-guide.md
          - customize.md
